version: '3.9'

services:
  welcomedb:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=welcomedb
      - POSTGRES_PASSWORD=welcomedb
      - POSTGRES_DB=welcomedb
  welcome_web:
    build: ./welcome_proj
    command: python /usr/src/welcome_proj/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./welcome_proj/:/usr/src/welcome_proj
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - welcomedb

volumes:
  postgres_data:
